---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: awx-prerequisites.yml

- name: Install AWX dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ awx_package_dependencies }}"

- import_tasks: set_image.yml

- import_tasks: standalone.yml

