---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: awx-prerequisites.yml

- name: Install AWX dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ awx_package_dependencies }}"

- name: Clone AWX into configured directory.
  git:
    repo: "{{ awx_repo }}"
    dest: "{{ awx_repo_dir }}"
    version: "{{ awx_version }}"
    update: "{{ awx_keep_updated }}"
    force: yes
    accept_hostkey: yes

- name: Copy awx invetory 
  template:
    src: inventory.j2
    dest: "{{ awx_repo_dir }}/installer/inventory"

- name: Run the AWX installation playbook.
  command: "ansible-playbook -i inventory install.yml"
  args:
    chdir: "{{ awx_repo_dir }}/installer"
